export const rulesWithFines = [
    { rule: "Fashionably late to meetings?", fine: 50 },
    { rule: "Shoes playing hide and seek outside the rack!", fine: 30 },
    { rule: "Not refilling the water jug?", fine: 40 },
    { rule: "Borrowing without returning?", fine: 100 },
    { rule: "Leaving dishes in the sink overnight?", fine: 60 },
    { rule: "Ghosting messages in the team chat?", fine: 20 },
    { rule: "Chair spinning competitions during work hours?", fine: 30 },
    { rule: "Forgetting to mute on Zoom while munching?", fine: 50 },
    { rule: "Using someone else's coffee mug?", fine: 30 },
    { rule: "Leaving lights on in an empty room?", fine: 20 },
    { rule: "Singing off-key in the office?", fine: 10 },
    { rule: "Spamming 'Good Morning' in the group chat?", fine: 15 },
    { rule: "Forgetting office birthdays?", fine: 25 },
    { rule: "Taking the last snack without restocking?", fine: 70 },
    { rule: "Too many 'Ums' in presentations?", fine: 50 },
    { rule: "Accidentally hitting 'Reply All'?", fine: 100 },
    { rule: "Wearing sunglasses indoors like a rockstar?", fine: 20 },
  ];